### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by hooopo** [octocat/Spoon-Knife#791]
## TODO
- [ ] a task list item
- [ ] list syntax required
- [ ] normal **formatting**, @mentions, #1234 refs
- [x] completed
